export const PLANS = {
  free: {
    id: "free",
    name: "Free",
    price: 0,
    priceDisplay: "₹0",
    period: "forever",
    maxEvents: 1,
    maxStorageGB: 5,
    maxGuests: 100,
    features: [
      "5 GB storage",
      "1 event",
      "100 guests",
      "AI face search",
      "WhatsApp sharing",
      "PIN protection",
    ],
  },
  basic: {
    id: "basic",
    name: "Basic",
    price: 29900, // in paise for Razorpay
    priceDisplay: "₹299",
    period: "per event",
    maxEvents: 1,
    maxStorageGB: 15,
    maxGuests: 200,
    features: [
      "15 GB storage",
      "1 event",
      "200 guests",
      "AI face search",
      "WhatsApp + QR sharing",
      "PIN protection",
      "Full-res download",
    ],
  },
  standard: {
    id: "standard",
    name: "Standard",
    price: 44900,
    priceDisplay: "₹449",
    period: "per event",
    maxEvents: 3,
    maxStorageGB: 30,
    maxGuests: 500,
    popular: true,
    features: [
      "30 GB storage",
      "3 events",
      "500 guests",
      "AI face search",
      "WhatsApp + QR sharing",
      "PIN protection",
      "Full-res download",
      "Google Drive BYOC",
    ],
  },
  pro: {
    id: "pro",
    name: "Pro",
    price: 72000,
    priceDisplay: "₹720",
    period: "per event",
    maxEvents: 5,
    maxStorageGB: 50,
    maxGuests: -1, // -1 = unlimited
    features: [
      "50 GB storage",
      "5 events",
      "Unlimited guests",
      "AI face search",
      "WhatsApp + QR sharing",
      "PIN protection",
      "Full-res download",
      "Google Drive BYOC",
      "Priority support",
    ],
  },
  premium: {
    id: "premium",
    name: "Premium",
    price: 159900,
    priceDisplay: "₹1,599",
    period: "per event",
    maxEvents: -1, // -1 = unlimited
    maxStorageGB: 100,
    maxGuests: -1,
    features: [
      "100 GB storage",
      "Unlimited events",
      "Unlimited guests",
      "AI face search",
      "WhatsApp + QR sharing",
      "PIN protection",
      "Full-res download",
      "Google Drive BYOC",
      "Dedicated support",
      "Custom branding",
    ],
  },
} as const;

export type PlanId = keyof typeof PLANS;
export type Plan = (typeof PLANS)[PlanId];
