import type { Metadata } from "next";
import { FileText, AlertTriangle, Scale, Ban, CreditCard, Globe } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service — EventPix",
  description:
    "Terms and conditions for using the EventPix AI-powered event photo sharing platform.",
};

const sections = [
  {
    icon: <FileText className="h-5 w-5" />,
    title: "1. Acceptance of Terms",
    content: `By accessing or using EventPix ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not use the Service.

EventPix is operated by EventPix Technologies ("we", "us", "our"). The Service is available at eventpix.in and its subdomains.

We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the revised Terms. We will notify users of material changes via email.`,
  },
  {
    icon: <Scale className="h-5 w-5" />,
    title: "2. Service Description",
    content: `EventPix is an AI-powered event photo sharing platform that:

• Allows event hosts to upload and organize event photos
• Uses AWS Rekognition facial recognition technology to match guests with their photos
• Enables guests to find their photos by taking a selfie
• Provides sharing via WhatsApp, QR codes, and direct links
• Offers storage options including Google Drive (BYOC) and Cloudflare R2

The Service is provided "as is" and we do not guarantee 100% accuracy in face recognition results. Match accuracy depends on photo quality, lighting conditions, and facial visibility.`,
  },
  {
    icon: <FileText className="h-5 w-5" />,
    title: "3. User Accounts & Responsibilities",
    content: `**Account Creation:** You must provide accurate information when creating an account. You are responsible for maintaining the security of your account credentials.

**Host Responsibilities:** As an event host, you are responsible for:
• Obtaining consent from event attendees before uploading their photos
• Informing guests that AI face recognition will be used
• Ensuring you have the right to upload and share the photos
• Managing access via PIN codes for private events

**Guest Usage:** Guests using the face recognition feature consent to their selfie being processed for face matching. Selfies are processed in real-time and not permanently stored.

**Age Restriction:** You must be at least 18 years old to create a host account. Guests accessing event galleries must be at least 13 years old.`,
  },
  {
    icon: <Ban className="h-5 w-5" />,
    title: "4. Acceptable Use Policy",
    content: `You agree NOT to use EventPix for:

• Uploading illegal, harmful, or offensive content
• Uploading photos of individuals without their knowledge or consent
• Using face recognition for surveillance, stalking, or harassment
• Reverse-engineering or attempting to extract the AI models
• Automated scraping, crawling, or bulk downloading of photos
• Impersonating other individuals or creating fake events
• Uploading malware, viruses, or malicious code
• Any activity that violates applicable laws

We reserve the right to suspend or terminate accounts that violate these terms without notice.`,
  },
  {
    icon: <CreditCard className="h-5 w-5" />,
    title: "5. Pricing & Payments",
    content: `**Free Tier:** Available at no cost with limited features (1 event, 5GB storage, 100 guests).

**Paid Plans:** Pricing is per event as displayed on our pricing page. All prices are in Indian Rupees (₹) and inclusive of applicable taxes.

**Payment Processing:** Payments are processed securely through Razorpay. We accept UPI, credit/debit cards, net banking, and digital wallets.

**No Auto-Renewal:** Our plans are one-time per-event purchases, not recurring subscriptions. You will not be charged automatically.

**Refunds:** Please refer to our Refund Policy for details on cancellations and refunds.

**Plan Limits:** Each plan has defined limits on storage, number of events, and guest count. Exceeding these limits may require upgrading your plan.`,
  },
  {
    icon: <AlertTriangle className="h-5 w-5" />,
    title: "6. Intellectual Property",
    content: `**Your Content:** You retain full ownership of all photos and content you upload to EventPix. We do not claim any intellectual property rights over your content.

**License Grant:** By uploading content, you grant us a limited, non-exclusive license to host, process (including face indexing), and deliver your photos through the Service. This license terminates when your event or account is deleted.

**Our Property:** The EventPix name, logo, software, algorithms, and design are our intellectual property, protected by applicable laws. You may not copy, modify, or distribute our software without written permission.

**AI Processing:** Face embeddings generated by our AI are derived data used solely for matching purposes. These embeddings are not meaningful outside the context of our face matching system and are deleted with the associated event.`,
  },
  {
    icon: <AlertTriangle className="h-5 w-5" />,
    title: "7. Limitation of Liability",
    content: `To the maximum extent permitted by law:

• EventPix is provided "as is" without warranties of any kind, express or implied.
• We are not liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.
• Our total liability for any claim shall not exceed the amount you paid for the Service in the 12 months preceding the claim.
• We are not responsible for the accuracy of face recognition results.
• We are not liable for data loss due to events beyond our control (force majeure).

**Indemnification:** You agree to indemnify EventPix against any claims arising from your use of the Service, your content, or your violation of these Terms.`,
  },
  {
    icon: <Globe className="h-5 w-5" />,
    title: "8. Governing Law & Dispute Resolution",
    content: `These Terms are governed by the laws of India.

Any disputes arising out of these Terms shall be resolved through:
1. **Good Faith Negotiation:** We will first attempt to resolve disputes through direct communication.
2. **Mediation:** If negotiation fails, disputes will be submitted to mediation.
3. **Jurisdiction:** Any legal proceedings shall be filed exclusively in the courts of Indore, Madhya Pradesh, India.

**Severability:** If any provision of these Terms is found to be unenforceable, the remaining provisions shall continue in full force and effect.

**Contact:** For any questions about these Terms, contact us at legal@eventpix.in`,
  },
];

export default function TermsPage() {
  return (
    <div>
      {/* Header */}
      <div className="mb-12 text-center">
        <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-blue-200 bg-white/80 px-4 py-1.5 text-sm font-medium text-blue-700">
          <FileText className="h-4 w-4" />
          Terms of Service
        </div>
        <h1 className="mb-4 text-4xl font-extrabold text-slate-900">
          Terms of Service
        </h1>
        <p className="mx-auto max-w-2xl text-lg text-slate-500">
          Please read these terms carefully before using EventPix. By using our
          service, you agree to these terms.
        </p>
        <p className="mt-3 text-sm text-slate-400">
          Last updated: April 15, 2026
        </p>
      </div>

      {/* Sections */}
      <div className="space-y-6">
        {sections.map((section) => (
          <div
            key={section.title}
            className="rounded-2xl border border-blue-100 bg-white p-8 shadow-sm"
          >
            <div className="mb-4 flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-blue-500 to-sky-400 text-white">
                {section.icon}
              </div>
              <h2 className="text-xl font-bold text-slate-900">
                {section.title}
              </h2>
            </div>
            <div className="text-slate-600">
              {section.content.split("\n\n").map((para, i) => (
                <p key={i} className="mb-3 whitespace-pre-line leading-relaxed">
                  {para}
                </p>
              ))}
            </div>
          </div>
        ))}
      </div>

      {/* Contact */}
      <div className="mt-10 rounded-2xl border border-blue-100 bg-gradient-to-r from-blue-50 to-sky-50 p-8 text-center">
        <h3 className="mb-2 text-lg font-bold text-slate-900">
          Questions about our terms?
        </h3>
        <p className="text-slate-500">
          Contact us at{" "}
          <a
            href="mailto:legal@eventpix.in"
            className="font-medium text-blue-600 hover:underline"
          >
            legal@eventpix.in
          </a>
        </p>
      </div>
    </div>
  );
}
