"use client";

import Link from "next/link";
import { useState, Suspense } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Camera, Eye, EyeOff, MessageSquare, Phone, ArrowLeft } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { requestLoginOTP, verifyLoginAndGetLink } from "./actions";

type LoginMethod = "email" | "whatsapp";
type LoginStep = "request" | "verify";

function LoginForm() {
  const [method, setMethod] = useState<LoginMethod>("email");
  const [step, setStep] = useState<LoginStep>("request");
  
  // Email state
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  
  // WhatsApp state
  const [phone, setPhone] = useState("");
  const [otp, setOtp] = useState("");
  
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  
  const router = useRouter();
  const searchParams = useSearchParams();
  const linkExpired = searchParams.get("error") === "link-expired";
  const supabase = createClient();

  /**
   * Traditional Email/Password Login
   */
  async function handleEmailLogin(e: React.FormEvent) {
    e.preventDefault();
    setLoading(true);
    setError("");

    const { error } = await supabase.auth.signInWithPassword({ email, password });

    if (error) {
      setError(error.message);
      setLoading(false);
    } else {
      router.push("/dashboard");
      router.refresh();
    }
  }

  /**
   * WhatsApp OTP Login - Step 1: Request
   */
  async function handleRequestOTP(e: React.FormEvent) {
    e.preventDefault();
    setLoading(true);
    setError("");

    const result = await requestLoginOTP(phone);
    
    if (result.success) {
      setStep("verify");
    } else {
      setError(result.error || "Failed to send OTP.");
    }
    setLoading(false);
  }

  /**
   * WhatsApp OTP Login - Step 2: Verify & Redirect
   */
  async function handleVerifyOTP(e: React.FormEvent) {
    e.preventDefault();
    setLoading(true);
    setError("");

    const result = await verifyLoginAndGetLink(phone, otp);
    
    if (result.success && result.loginUrl) {
      // Magic Link Login - Redirect browser to the link generated by Supabase Admin
      window.location.href = result.loginUrl;
    } else {
      setError(result.error || "Verification failed.");
      setLoading(false);
    }
  }

  return (
    <div className="flex min-h-screen items-center justify-center bg-muted/30 px-4 py-12">
      <div className="w-full max-w-md">
        <div className="mb-8 text-center">
          <Link href="/" className="mb-4 inline-flex items-center gap-2">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary">
              <Camera className="h-6 w-6 text-primary-foreground" />
            </div>
            <span className="text-2xl font-bold">EventPix</span>
          </Link>
          <p className="mt-2 text-muted-foreground">
            {method === "email" ? "Welcome back! Sign in to manage your events." : "Sign in quickly using WhatsApp."}
          </p>
        </div>

        <div className="rounded-2xl border border-border bg-card p-8 shadow-sm">
          {error && (
            <div className="mb-6 rounded-lg bg-destructive/10 p-3 text-sm text-destructive">
              {error}
            </div>
          )}

          {method === "email" ? (
            /* --- EMAIL LOGIN FORM --- */
            <form onSubmit={handleEmailLogin} className="space-y-4">
              <div>
                <label className="mb-1.5 block text-sm font-medium">Email</label>
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                  className="w-full rounded-lg border border-border bg-background px-3.5 py-2.5 text-sm outline-none transition focus:border-primary"
                  placeholder="you@example.com"
                />
              </div>

              <div>
                <div className="mb-1.5 flex items-center justify-between">
                  <label className="text-sm font-medium">Password</label>
                  <Link href="/forgot-password" className="text-xs text-muted-foreground hover:text-primary">
                    Forgot?
                  </Link>
                </div>
                <div className="relative">
                  <input
                    type={showPassword ? "text" : "password"}
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    required
                    className="w-full rounded-lg border border-border bg-background px-3.5 py-2.5 pr-10 text-sm outline-none transition focus:border-primary"
                    placeholder="Your password"
                  />
                  <button
                    type="button"
                    onClick={() => setShowPassword((v) => !v)}
                    className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground"
                  >
                    {showPassword ? <EyeOff size={16} /> : <Eye size={16} />}
                  </button>
                </div>
              </div>

              <button
                type="submit"
                disabled={loading}
                className="w-full rounded-lg bg-primary py-2.5 text-sm font-semibold text-primary-foreground transition hover:bg-primary/90 disabled:opacity-50"
              >
                {loading ? "Signing in..." : "Sign in"}
              </button>

              <div className="relative my-6">
                <div className="absolute inset-0 flex items-center"><span className="w-full border-t border-border"></span></div>
                <div className="relative flex justify-center text-xs uppercase"><span className="bg-card px-2 text-muted-foreground">Or continue with</span></div>
              </div>

              <button
                type="button"
                onClick={() => setMethod("whatsapp")}
                className="w-full flex items-center justify-center gap-2 rounded-lg border border-border bg-background py-2.5 text-sm font-medium transition hover:bg-muted"
              >
                <MessageSquare size={16} className="text-green-600" />
                Login with WhatsApp
              </button>
            </form>
          ) : (
            /* --- WHATSAPP LOGIN FORM --- */
            <div className="space-y-6">
              {step === "request" ? (
                <form onSubmit={handleRequestOTP} className="space-y-4">
                  <div>
                    <label className="mb-1.5 block text-sm font-medium">WhatsApp Number</label>
                    <div className="relative">
                      <span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-muted-foreground text-sm">+91</span>
                      <input
                        type="tel"
                        value={phone}
                        onChange={(e) => setPhone(e.target.value.replace(/\D/g, '').slice(0, 10))}
                        required
                        className="w-full rounded-lg border border-border bg-background px-3.5 py-2.5 pl-12 text-sm outline-none transition focus:border-primary"
                        placeholder="9876543210"
                        autoFocus
                      />
                    </div>
                  </div>

                  <button
                    type="submit"
                    disabled={loading || phone.length < 10}
                    className="w-full flex items-center justify-center gap-2 rounded-lg bg-green-600 py-2.5 text-sm font-semibold text-white transition hover:bg-green-700 disabled:opacity-50"
                  >
                    {loading ? "Sending Code..." : "Get Login OTP"}
                    <MessageSquare size={16} />
                  </button>
                </form>
              ) : (
                <form onSubmit={handleVerifyOTP} className="space-y-6">
                  <div className="text-center">
                    <p className="text-sm text-muted-foreground">We sent a code to <strong>+91 {phone}</strong></p>
                  </div>
                  <input
                    type="text"
                    value={otp}
                    onChange={(e) => setOtp(e.target.value.replace(/\D/g, '').slice(0, 6))}
                    required
                    maxLength={6}
                    autoFocus
                    className="w-full text-center text-2xl font-bold tracking-[0.5em] rounded-lg border border-border bg-background py-3 outline-none focus:border-primary"
                    placeholder="000000"
                  />
                  <button
                    type="submit"
                    disabled={loading || otp.length < 6}
                    className="w-full rounded-lg bg-primary py-2.5 text-sm font-semibold text-primary-foreground transition hover:bg-primary/90"
                  >
                    {loading ? "Verifying..." : "Verify & Sign In"}
                  </button>
                  <button type="button" onClick={() => setStep("request")} className="w-full text-xs text-muted-foreground hover:underline">Resend code or change number</button>
                </form>
              )}

              <button
                type="button"
                onClick={() => { setMethod("email"); setStep("request"); }}
                className="w-full flex items-center justify-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground pt-2"
              >
                <ArrowLeft size={14} />
                Back to Email Login
              </button>
            </div>
          )}
        </div>

        <p className="mt-8 text-center text-sm text-muted-foreground">
          Don&apos;t have an account?{" "}
          <Link href="/signup" className="font-medium text-primary hover:underline">
            Sign up
          </Link>
        </p>
      </div>
    </div>
  );
}

export default function LoginPage() {
  return (
    <Suspense>
      <LoginForm />
    </Suspense>
  );
}
